apiVersion: v1
kind: Secret
metadata:
  namespace: ${namespace_name}
  name: ${secret_name}
  manifest_fingerprint: ${manifest_fingerprint}
data:
  client_id: ${client_id}
  client_secret: ${client_secret}
type: Opaque