apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
 name: _name
 namespace: ${namespace}
spec:
 refreshInterval: 1m           
 secretStoreRef:
   kind: SecretStore
   name: gcp-store            
 target:
   name:  _name   #secret_to_be_created in k8s
   template:
    metadata:
      annotations:
        reloader.stakater.com/match: "true"
   creationPolicy: Owner
 dataFrom:
 - extract:
    key: _gcpsm  #name_of_GCPSM key
    